version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "28018:27017"
    restart: always
    volumes:
      - mongo-data:/data/db

  graphql:
    build:
      context: .
    container_name: graphql-server
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      MONGO_URI: mongodb://db:28018/salemanagement
    volumes:
      - D:/:/app/uploads/

  # my-service:
  #   image: alpine
  #   volumes:
  #     - D:/:/mnt
  #   command: sh -c "while true; do sleep 3600; done"

volumes:
  mongo-data:
